### ISSUE TITLE
Option -Xcollection-setter-injector does not work

### ISSUE THREAD

**Issue by istvan-hegedus** [bjornvester/wsdl2java-gradle-plugin#26]
I tried to configure the `wsdl2java` plugin with `-Xcollection-setter-injector` as follows:
```
wsdl2java {
	options.add("-xjc-Xcollection-setter-injector")
	wsdlDir = layout.projectDirectory
	includesWithOptions = ["src/main/resources/wsdl/service.wsdl" : ["-wsdlLocation", "http://localhost/wsdl/service.wsdl"]
	cxfVersion = "4.0.2"
	useJakarta = true
}
```

Without the option everything works as expected, but with the option I got the following exception:
```
...
Caused by: java.lang.NoSuchMethodError: 'com.sun.xml.bind.api.impl.NameConverter com.sun.tools.xjc.model.Model.getNameConverter()'
        at com.sun.tools.xjc.addon.collection_setter_injector.PluginImpl.declareMethod(PluginImpl.java:169)
        at com.sun.tools.xjc.addon.collection_setter_injector.PluginImpl.run(PluginImpl.java:142)
        at com.sun.tools.xjc.model.Model.generateCode(Model.java:262)
        at com.sun.tools.xjc.api.impl.s2j.SchemaCompilerImpl.bind(SchemaCompilerImpl.java:255)
        at com.sun.tools.xjc.api.impl.s2j.SchemaCompilerImpl.bind(SchemaCompilerImpl.java:67)
        at org.apache.cxf.tools.wsdlto.databinding.jaxb.JAXBDataBinding.initialize(JAXBDataBinding.java:445)
        at org.apache.cxf.tools.wsdlto.WSDLToJavaContainer.generateTypes(WSDLToJavaContainer.java:711)
        at org.apache.cxf.tools.wsdlto.WSDLToJavaContainer.processWsdl(WSDLToJavaContainer.java:259)
        at org.apache.cxf.tools.wsdlto.WSDLToJavaContainer.execute(WSDLToJavaContainer.java:156)
        at org.apache.cxf.tools.wsdlto.WSDLToJavaContainer.execute(WSDLToJavaContainer.java:402)
        at org.apache.cxf.tools.common.toolspec.ToolRunner.runTool(ToolRunner.java:105)
        at org.apache.cxf.tools.wsdlto.WSDLToJava.run(WSDLToJava.java:113)
        at org.apache.cxf.tools.wsdlto.WSDLToJava.run(WSDLToJava.java:86)
        at com.github.bjornvester.wsdl2java.Wsdl2JavaWorker.execute(Wsdl2JavaWorker.kt:18)
...
```

Dependencies:
```
wsdl2java
+--- org.apache.cxf:cxf-tools-wsdlto-frontend-jaxws:4.0.2
|    +--- org.apache.cxf:cxf-tools-common:4.0.2
|    |    +--- jakarta.jws:jakarta.jws-api:3.0.0
|    |    +--- org.apache.velocity:velocity-engine-core:2.3
|    |    |    +--- org.apache.commons:commons-lang3:3.11
|    |    |    \--- org.slf4j:slf4j-api:1.7.30 -> 1.7.36
|    |    +--- wsdl4j:wsdl4j:1.6.3
|    |    +--- org.glassfish.jaxb:jaxb-xjc:3.0.2
|    |    |    +--- org.glassfish.jaxb:jaxb-core:3.0.2
|    |    |    |    +--- jakarta.xml.bind:jakarta.xml.bind-api:3.0.1
|    |    |    |    |    \--- com.sun.activation:jakarta.activation:2.0.1
|    |    |    |    +--- org.glassfish.jaxb:txw2:3.0.2
|    |    |    |    \--- com.sun.istack:istack-commons-runtime:4.0.1
|    |    |    +--- org.glassfish.jaxb:xsom:3.0.2
|    |    |    |    \--- com.sun.xml.bind.external:relaxng-datatype:3.0.2
|    |    |    +--- org.glassfish.jaxb:codemodel:3.0.2
|    |    |    +--- com.sun.xml.bind.external:rngom:3.0.2
|    |    |    |    \--- com.sun.xml.bind.external:relaxng-datatype:3.0.2
|    |    |    +--- com.sun.xml.dtd-parser:dtd-parser:1.4.5
|    |    |    \--- com.sun.istack:istack-commons-tools:4.0.1
|    |    +--- org.glassfish.jaxb:jaxb-runtime:3.0.2
|    |    |    \--- org.glassfish.jaxb:jaxb-core:3.0.2 (*)
|    |    +--- org.apache.cxf:cxf-core:4.0.2
|    |    |    +--- jakarta.annotation:jakarta.annotation-api:2.1.1
|    |    |    +--- org.glassfish.jaxb:jaxb-runtime:3.0.2 (*)
|    |    |    +--- com.fasterxml.woodstox:woodstox-core:6.5.1
|    |    |    |    \--- org.codehaus.woodstox:stax2-api:4.2.1
|    |    |    +--- org.apache.ws.xmlschema:xmlschema-core:2.3.0
|    |    |    +--- org.eclipse.angus:angus-activation:2.0.1
|    |    |    |    \--- jakarta.activation:jakarta.activation-api:2.1.2
|    |    |    \--- jakarta.xml.bind:jakarta.xml.bind-api:3.0.1 (*)
|    |    \--- com.fasterxml.woodstox:woodstox-core:6.5.1 (*)
|    +--- xml-resolver:xml-resolver:1.2
|    +--- org.apache.cxf:cxf-core:4.0.2 (*)
|    +--- org.apache.cxf:cxf-tools-wsdlto-core:4.0.2
|    |    +--- org.apache.cxf:cxf-tools-common:4.0.2 (*)
|    |    +--- org.apache.cxf:cxf-tools-validator:4.0.2
|    |    |    +--- org.apache.cxf:cxf-tools-common:4.0.2 (*)
|    |    |    +--- wsdl4j:wsdl4j:1.6.3
|    |    |    +--- org.glassfish.jaxb:jaxb-xjc:3.0.2 (*)
|    |    |    +--- org.glassfish.jaxb:jaxb-runtime:3.0.2 (*)
|    |    |    +--- org.apache.ws.xmlschema:xmlschema-core:2.3.0
|    |    |    +--- org.apache.cxf:cxf-core:4.0.2 (*)
|    |    |    \--- org.apache.cxf:cxf-rt-bindings-soap:4.0.2
|    |    |         +--- jakarta.xml.soap:jakarta.xml.soap-api:2.0.1
|    |    |         |    \--- com.sun.activation:jakarta.activation:2.0.1
|    |    |         +--- jakarta.jws:jakarta.jws-api:3.0.0
|    |    |         +--- jakarta.xml.ws:jakarta.xml.ws-api:3.0.1
|    |    |         |    +--- jakarta.xml.bind:jakarta.xml.bind-api:3.0.1 (*)
|    |    |         |    +--- jakarta.xml.soap:jakarta.xml.soap-api:2.0.1 (*)
|    |    |         |    \--- jakarta.jws:jakarta.jws-api:3.0.0
|    |    |         +--- org.apache.cxf:cxf-core:4.0.2 (*)
|    |    |         +--- org.apache.cxf:cxf-rt-wsdl:4.0.2
|    |    |         |    +--- org.apache.cxf:cxf-core:4.0.2 (*)
|    |    |         |    +--- wsdl4j:wsdl4j:1.6.3
|    |    |         |    \--- org.ow2.asm:asm:9.5
|    |    |         +--- org.apache.cxf:cxf-rt-databinding-jaxb:4.0.2
|    |    |         |    +--- org.apache.cxf:cxf-core:4.0.2 (*)
|    |    |         |    \--- org.apache.cxf:cxf-rt-wsdl:4.0.2 (*)
|    |    |         \--- org.eclipse.angus:angus-activation:2.0.1 (*)
|    |    +--- org.apache.cxf:cxf-core:4.0.2 (*)
|    |    +--- org.apache.cxf:cxf-rt-wsdl:4.0.2 (*)
|    |    +--- wsdl4j:wsdl4j:1.6.3
|    |    +--- org.glassfish.jaxb:jaxb-xjc:3.0.2 (*)
|    |    \--- org.glassfish.jaxb:jaxb-runtime:3.0.2 (*)
|    \--- org.apache.commons:commons-text:1.10.0
+--- org.apache.cxf:cxf-tools-wsdlto-databinding-jaxb:4.0.2
|    +--- org.glassfish.jaxb:jaxb-xjc:3.0.2 (*)
|    +--- org.glassfish.jaxb:jaxb-runtime:3.0.2 (*)
|    +--- org.apache.cxf:cxf-tools-wsdlto-core:4.0.2 (*)
|    \--- org.apache.cxf:cxf-tools-common:4.0.2 (*)
+--- jakarta.xml.ws:jakarta.xml.ws-api:3.0.1 (*)
+--- jakarta.annotation:jakarta.annotation-api:2.1.1
\--- org.slf4j:slf4j-simple:1.7.36
     \--- org.slf4j:slf4j-api:1.7.36
```

Do you have any idea what kind of dependency is missing?

Thank you for your help in advance.

**Comment by istvan-hegedus** [comment]
I forked the `org.andromda.thirdparty.jaxb2_commons:collection-setter-injector:1.0` with a simple modification of `import com.sun.xml.bind.api.impl.NameConverter;` => `import org.glassfish.jaxb.core.api.impl.NameConverter;` in the `com.sun.tools.xjc.addon.collection_setter_injector.PluginImpl` and it started to work.
If you know an already patched artifact, let me know. Thanks!

**Comment by AsifAkbarMohideen** [comment]
When we fork the org.andromda.thirdparty.jaxb2_commons:collection-setter-injector:1.0 jar and modify as per above suggestion try to generate the setter adding it as dependency to wsdl2java plugin getting teh below error

 Caused by: org.xml.sax.SAXParseException; systemId:    repository/org/apache/cxf/cxf-tools-common/4.0.2/cxf-tools-common-4.0.2.jar!/org/apache/cxf/tools/common/jaxb/W3CEPRJaxbBinding_jaxb22.xml; lineNumber: 20; columnNumber: 161; Unexpected <bindings> appears at line 20 column 161
[WARNING] 	at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.unexpectedX(NGCCRuntimeEx.java:488)
[WARNING] 	at com.sun.xml.xsom.impl.parser.state.NGCCHandler.unexpectedEnterElement(NGCCHandler.java:155)
[WARNING] 	at com.sun.xml.xsom.impl.parser.state.Schema.enterElement(Schema.java:377)
[WARNING] 	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.startElement(NGCCRuntime.java:219)
[WARNING] 	at java.xml/org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:539)
[WARNING] 	at com.sun.tools.xjc.util.SubtreeCutter.startElement(SubtreeCutter.java:104)
